In [2]:
import yfinance as yf

ticker = "2330.TW"  # 台積電

df = yf.download(
    ticker,
    start="2020-01-01",
    end="2024-12-31",
    interval="1d",
    auto_adjust=False
)

df.tail()

[*********************100%***********************]  1 of 1 completed

Price         Adj Close   Close    High     Low    Open    Volume
Ticker          2330.TW 2330.TW 2330.TW 2330.TW 2330.TW   2330.TW
Date
2024-12-24  1056.366577  1080.0  1095.0  1080.0  1095.0  26461906
2024-12-25  1061.257080  1085.0  1090.0  1080.0  1090.0  15481622
2024-12-26  1061.257080  1085.0  1090.0  1085.0  1085.0  14374900
2024-12-27  1066.147583  1090.0  1095.0  1080.0  1080.0  24948385
2024-12-30  1066.147583  1090.0  1095.0  1085.0  1090.0  23954634

In [3]:
df = yf.download(
    "2330.TW",
    period="5d",
    interval="1d",
    auto_adjust=False
)
df

[*********************100%***********************]  1 of 1 completed

Price      Adj Close   Close    High     Low    Open    Volume
Ticker       2330.TW 2330.TW 2330.TW 2330.TW 2330.TW   2330.TW
Date
2026-06-29    2370.0  2370.0  2395.0  2330.0  2330.0  33267315
2026-06-30    2410.0  2410.0  2475.0  2410.0  2440.0  42933128
2026-07-01    2505.0  2505.0  2505.0  2475.0  2495.0  30489002
2026-07-02    2465.0  2465.0  2480.0  2445.0  2450.0  27485121
2026-07-03    2445.0  2445.0  2465.0  2415.0  2415.0  26489446

In [4]:
close_df = df['Close'].reset_index()
close_df

Ticker       Date  2330.TW
0      2026-06-29   2370.0
1      2026-06-30   2410.0
2      2026-07-01   2505.0
3      2026-07-02   2465.0
4      2026-07-03   2445.0

In [18]:
ticker = ["2330.TW", "0050.TW", "0056.TW", "006208.TW"] 

df1 = yf.download(
    ticker,
    start="2026-01-01",
    end="2026-07-04",
    interval="1mo"
)

final_df = df1['Close'].reset_index()
final_df

[*********************100%***********************]  4 of 4 completed

Ticker       Date     0050.TW    0056.TW   006208.TW      2330.TW
0      2026-01-01   72.599998  36.698048  168.050003  1764.520142
1      2026-02-01   81.150002  39.344448  188.000000  1983.221313
2      2026-03-01   72.349998  36.258610  168.100006  1755.317139
3      2026-04-01   90.500000  40.900002  209.750000  2129.319336
4      2026-05-01  105.400002  50.200001  241.250000  2348.733887
5      2026-06-01  107.800003  53.250000  250.199997  2410.000000
6      2026-07-01  108.349998  52.849998  251.350006  2445.000000